pipeline {
  agent any
  stages{
       stage ('Clean up'){
        steps{
            delereDir()
        }
        stage("Clone Repo"){
            steps{
               sh "git clone https://github.com/IBraun888/jenkins_hello_world.git" 
            }
        }
        stage("Build")
    }
} 
  