pipeline {
  agent any
  stages{
       stage ("Clean up"){
        steps{
            deleteDir()
        }
        stage("Clone Repo"){
            steps{
               sh "git clone https://github.com/IBraun888/jenkins_hello_world.git" 
            }
        }
        stage("Build"){
            steps{
                dir('jenkins-hello-world'){
                    sh "mvn clean install"
                }
            }
        }
        stage("Test"){
            steps{
                 dir('jenkins-hello-world'){
                    sh "mvn test"
            }
        }
    }
}   
}
  