pipeline {
    agent any

parameters{
    string(defaultValue: "Test", description: "Which end here", name: "deploy End")
}

stages {
    stage("Demo"){
        steps {
            echo "boolean ${params.deployEnv}"
        }
    }
}
}
  